name: CI

on: [push, pull_request]

env:
  UNITY_VERSION: 2020.2.6

jobs:

  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          submodules: recursive

      - name: Cache Unity installation
        id: cache-unity
        uses: actions/cache@v2
        with:
          path: C:/Program Files/Unity
          key: ${{ env.UNITY_VERSION }}

      - name: Install Unity
        run: choco install unity --version ${{ env.UNITY_VERSION }} --yes --no-progress
        if: ${{ !steps.cache-unity.outputs.cache-hit }}

      - name: Add Unity on PATH
        run: |
          echo "C:\Program Files\Unity\Editor" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo where unity

      - name: Activate license
        run: unity -quit -batchmode -nographics -logFile - -username ${{ secrets.UNITY_EMAIL }} -password ${{ secrets.UNITY_PASSWORD }} -serial ${{ secrets.UNITY_SERIAL }}

      - name: Build project
        run: unity -quit -batchmode -nographics -logFile - -projectPath "${{ env.GITHUB_WORKSPACE }}/samples/unity-of-bugs" -buildWindows64Player "${{ env.GITHUB_WORKSPACE }}/buildOutput/build.exe"

      - name: Return license
        run: unity -quit -batchmode -nographics -logFile - -returnlicense
        if: ${{ always() }}

      - name: Aggregate Unity logs
        run: |
          mkdir unityLogs
          cp $env:LocalAppData/Unity/Editor/Editor.log unityLogs/Editor.log
          cp $env:LocalAppData/Unity/Editor/upm.log unityLogs/UPM.log

      - name: Upload Unity logs
        uses: actions/upload-artifact@v1
        with:
          name: Unity logs
          path: unityLogs

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Build output
          path: buildOutput
