name: CI

on: [push, pull_request]

env:
  UNITY_VERSION: 2020.2.6
  PROJECT_PATH: samples/unity-of-bugs

jobs:

  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          submodules: recursive

      - name: Restore cached Unity installation
        id: cache-unity
        uses: actions/cache@v2
        with:
          path: C:/Program Files/Unity
          # Replace the trailing hash to reset cache,
          # in case the instalation step has been changed.
          key: ${{ env.UNITY_VERSION }}-bf30a

      - name: Install Unity
        run: |
          choco install unity --version ${{ env.UNITY_VERSION }} --yes --no-progress
          choco install unity-win-il2cpp --version ${{ env.UNITY_VERSION }} --yes --no-progress
        if: ${{ !steps.cache-unity.outputs.cache-hit }}

      - name: Add Unity on PATH
        run: |
          echo "C:\Program Files\Unity\Editor" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          ls "C:\Program Files\Unity\Editor"

      - name: Activate license
        run: |
          unity -quit -batchmode -nographics -logFile - -serial ${{ secrets.UNITY_SERIAL }} -username ${{ secrets.UNITY_EMAIL }} -password ${{ secrets.UNITY_PASSWORD }} | Out-Default

      - name: Build project
        run: |
          unity -quit -batchmode -nographics -logFile - -projectPath ${{ env.PROJECT_PATH }} -buildWindows64Player artifacts/build.exe | Out-Default

      - name: Return license
        run: |
          unity -quit -batchmode -nographics -logFile - -returnlicense | Out-Default
        if: ${{ always() }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Build output
          path: ${{ env.PROJECT_PATH }}/artifacts
