name: CI

on: [push, pull_request]

env:
  UNITY_VERSION: 2020.2.6
  PROJECT_PATH: samples/unity-of-bugs

jobs:

  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          submodules: recursive

      - name: Restore cached Unity installation
        id: cache-unity
        uses: actions/cache@v2
        with:
          path: C:/Program Files/Unity
          key: ${{ env.UNITY_VERSION }}

      - name: Install Unity
        run: choco install unity --version ${{ env.UNITY_VERSION }} --yes --no-progress
        if: ${{ !steps.cache-unity.outputs.cache-hit }}

      # Ideally this should also be cached in the previous step but
      # but I haven't been able to figure out where these modules are installed.
      - name: Install build targets
        run: choco install unity-win-il2cpp --version ${{ env.UNITY_VERSION }} --yes --no-progress

      - name: Add Unity on PATH
        run: |
          echo "C:\Program Files\Unity\Editor" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          tree /F "C:\Program Files\Unity\Editor"

      - name: Activate license
        run: |
          unity -quit -batchmode -nographics -logFile - -serial ${{ secrets.UNITY_SERIAL }} -username ${{ secrets.UNITY_EMAIL }} -password ${{ secrets.UNITY_PASSWORD }} | Out-Default

      - name: Build project
        run: |
          unity -quit -batchmode -nographics -logFile - -projectPath ${{ env.PROJECT_PATH }} -buildWindows64Player "${{ env.PROJECT_PATH }}/artifacts/build.exe" | Out-Default

          echo "Project directory:"
          tree /F ${{ env.PROJECT_PATH }}

      - name: Return license
        run: |
          unity -quit -batchmode -nographics -logFile - -returnlicense | Out-Default
        if: ${{ always() }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Build output
          path: ${{ env.PROJECT_PATH }}/artifacts
