name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          submodules: recursive

      - name: Install Unity
        run: choco install unity

      - name: Add Unity on PATH
        run: echo "C:\Program Files\Unity\Editor" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: Activate license
        run: Unity -quit -batchmode -username ${{ secrets.UNITY_EMAIL }} -password ${{ secrets.UNITY_PASSWORD }} -serial ${{ secrets.UNITY_SERIAL }}

      - name: Build project
        run: Unity -quit -batchmode -projectPath "samples/unity-of-bugs" -buildWindows64Player "/buildOutput/build.exe"

      - name: Return license
        run: Unity -quit -batchmode -returnlicense
        if: ${{ always() }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Build output
          path: samples/unity-of-bugs/buildOutput
